### ISSUE TITLE
Fails to install on Linux - works on windows

### ISSUE THREAD

**Issue by MikeEckels** [kdschlosser/lv_cpython#14]
I am running Ubuntu 22.04. I am unable to install the package from pip. I run the command `python -m pip install lvgl` and it fails, appearing to be an issue with not being able to source a directory for an import statement in the setup.py. I have also tried installing the package manually by cloning the git using `git clone --recurse-submodules <git url>`, installing all dependencies and running `python -m pip install .` inside a venv. Still no dice. Oddly, however, this package installs perfectly normally on windows running the same python3.11+ versions.

Here is trace when tyring to build using `python -m pip install lvlg`:
```
python -m pip install lvgl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting lvgl
  Using cached lvgl-0.1.1b0.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/pi/Desktop/lvglTesting/testTwo/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pi/Desktop/lvglTesting/testTwo/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pi/Desktop/lvglTesting/testTwo/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-73aiy93g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-73aiy93g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-73aiy93g/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'builder'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

any help would be greatly appreciated!

**Comment by MikeEckels** [comment]
I have tracked down the issue, and have successfully built on windows and Ubuntu. The following is how to achieve a working build on Ubuntu 22.04.

1. Create a python virtual environment: `python3 -m venv .venv`
2. Clone **_lv_cpython_** in desired directory: `git clone git@github.com:kdschlosser/lv_cpython.git`
3. cd into the repo, and revert to the last working commit: `git checkout 8d4c1ef262d0eb3c064f3eed750b9dc0b21589db`. This is required because the most recent commit added git submodules which break the build.
4. Install build dependencies: `sudo apt install make libudev-dev g++ libsdl2-dev`
5. cd into .venv and activate
6. Updat evnironment packages: `python -m pip install --upgrade pip setuptools wheel build`
7. Install python dev: `sudo apt install python3-dev`
8. Build lvgl: `python -m pip install .`
9. Fix examples: Some examples require "User-Data" parameter in some functions. Just add the python `None` type.
