### ISSUE TITLE
Fails to install on Linux from the repository

### ISSUE THREAD

**Issue by phdru** [kdschlosser/lv_cpython#15]
Ubuntu 24.04.1 LTS, Python 3.12.3, pip 24.0
```sh
$ git clone --depth=1 https://github.com/kdschlosser/lv_cpython.git
$ cd lv_cpython/
$ git submodule update --depth=1 --init --recursive
$ CFLAGS=-Isrc pip install .
```
The error message is:
```
      Traceback (most recent call last):
        File "/tmp/lvgl-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/lvgl-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/lvgl-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 295, in <module>
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-tw_lj06e/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/lv_cpython/builder/build.py", line 34, in run
          py_builder.run(lvgl_output_path, self.ast)
        File "/tmp/lv_cpython/builder/py_builder.py", line 1743, in run
          node.gen_py()
        File "/tmp/lv_cpython/builder/py_builder.py", line 1155, in gen_py
          param_name + ': ' + str(param_type)
          ~~~~~~~~~~~^~~~~~
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by MikeEckels** [comment]
Although the install still fails with `pip install lvgl`, I have found a solution to build and install manually. I detail this process in #14.
The issue appears to main be with the introduction of git submodules.
